version: '3.8'

services:
  docker-demo:
    image: ${DOCKER_IMAGE_NAME}:${BUILD_NUMBER:-latest}
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - demo-network
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - demo-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  demo-network:
    driver: bridge