version: '3.8'

services:
  docker-demo:
    image: ${DOCKER_IMAGE_NAME}:${BUILD_NUMBER:-latest}
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - demo-network

  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
#    environment:
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - demo-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  demo-network:
    driver: bridge