version: '3.8'

services:
  docker-demo:
    image: ${DOCKER_IMAGE_NAME}:${BUILD_NUMBER:-latest}
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
#    environment:
#      - PORT=${PORT}
#      - SPRING_APP_NAME=${SPRING_APP_NAME}
#      - APP_DEMO=${APP_DEMO}
    restart: unless-stopped
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge