server:
  port: ${PORT:8082}

spring:
  application:
    name: ${SPRING_APP_NAME:demo}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  cloud:
    config:
      enabled: false

  config:
    import: optional:configserver

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8190/eureka/

application:
  demo: ${APP_DEMO:DOCKER-DEMO}



